all:
	make -C basic_tests
	make -C ft_cat_tests
	make -C ft_puts_tests

clean:
	make -C basic_tests clean
	make -C ft_cat_tests clean
	make -C ft_puts_tests clean

fclean:
	make -C basic_tests fclean
	make -C ft_cat_tests fclean
	make -C ft_puts_tests fclean

re:
	make -C basic_tests re
	make -C ft_cat_tests re
	make -C ft_puts_tests re
